#生产环境
spring:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://database-1.cn0omcun1jpr.us-east-1.rds.amazonaws.com:3306/daily?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=UTC
      username: root
      password: root
    jpa:
      hibernate:
        ddl-auto: none
      show-sql: true
logging:
  level:
    root: warn
    com.lh: info
  file: log/daily-pro.log
server:
  port: 5000
